# Generated by Django 5.2.6 on 2025-10-15 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='is_active',
            new_name='activo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='first_name',
            new_name='apellido',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='role',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='status',
            new_name='estado',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='date_joined',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_session_ip',
            new_name='ip_sesion',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='last_name',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='is_staff',
            new_name='staff',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='phone',
            new_name='telefono',
        ),
        migrations.RenameField(
            model_name='usuario',
            old_name='username',
            new_name='usuario',
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultimo_acceso',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
    ]
