# Generated by Django 5.2.6 on 2025-10-15 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_is_active_usuario_activo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
