# Generated by Django 5.2.6 on 2025-10-15 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bodega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('ubicacion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='control_por_lote',
            field=models.BooleanField(default=False, verbose_name='Control por Lote'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='control_por_serie',
            field=models.BooleanField(default=False, verbose_name='Control por Serie'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='perishable',
            field=models.BooleanField(default=False, verbose_name='Es Perecible'),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='serie',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='bodega',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion.bodega'),
        ),
    ]
