# Generated by Django 5.2.6 on 2025-10-15 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_bodega_movimientoinventario_control_por_lote_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'verbose_name': 'Proveedor', 'verbose_name_plural': 'Proveedores'},
        ),
    ]
