# Generated by Django 5.2.6 on 2025-10-14 14:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_remove_trabajador_cargo_remove_pedido_cliente_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ean_upc (opcional, único si se usa)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='modelo',
            field=models.TextField(blank=True, null=True, verbose_name='modelo (opcional)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogo.categoria', verbose_name='categoria (requerido)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True, verbose_name='descripción (opcional)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='marca (opcional)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='nombre (requerido)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio_venta',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='(requerido, único)'),
        ),
    ]
