# Generated by Django 5.2.6 on 2025-10-14 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_producto_ean_upc_producto_modelo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('caja', 'Caja'), ('uni', 'Unidad')], default='un', max_length=10, verbose_name='uom_compra (requerido)'),
        ),
        migrations.AddField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('caja', 'Caja'), ('uni', 'Unidad')], default='un', max_length=10, verbose_name='uom_venta (requerido)'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='modelo (opcional)'),
        ),
    ]
