# Generated by Django 5.2.6 on 2025-10-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_uom_compra_producto_uom_venta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='control_por_serie',
            field=models.BooleanField(default=False, verbose_name='Control por Serie'),
        ),
        migrations.AddField(
            model_name='producto',
            name='costo_estandar',
            field=models.PositiveIntegerField(blank=True, default=1, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='factor_conversion',
            field=models.PositiveIntegerField(default=1, null=True, verbose_name='factor de conversion'),
        ),
        migrations.AlterField(
            model_name='producto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='ean_upc',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='marca',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='modelo',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='producto',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_compra',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('caja', 'Caja'), ('uni', 'Unidad')], default='un', max_length=10),
        ),
        migrations.AlterField(
            model_name='producto',
            name='uom_venta',
            field=models.CharField(choices=[('kg', 'Kilogramo'), ('caja', 'Caja'), ('uni', 'Unidad')], default='un', max_length=10),
        ),
    ]
