# Generated by Django 5.2.6 on 2025-10-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0008_producto_control_por_serie_producto_costo_estandar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='punto_reorden',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='producto',
            name='stock_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Stock Total'),
        ),
    ]
